server:
  port: 8085

#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/moviesystem?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    # HikariDataSource存在jdbc的jar包里面
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
